language: node_js
node_js:
  - "8.0"

before_script:
  - yarn add stabuilder

script: "yarn run build"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

branches:
  only:
  - dev
  - preview