language: node_js
node_js:
  - "8.0"

before_script:
  - yarn add stabuilder

script: "yarn build"

cache:
  directories:
    - node_modules

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  local-dir: out
  on:
    branch: dev

branches:
  only:
  - dev
